### ISSUE TITLE
Support light color schemes.

### ISSUE THREAD

**Issue by Zoltu** [jacogr/atom-gulp-control#16]
Note: this may be a problem with gulp, not gulp-control.

I use a light theme and the white text doesn't get changed to black text when displayed on a white background.  This leads to output that looks like:
![image](https://cloud.githubusercontent.com/assets/886059/8022240/38b11e76-0c7a-11e5-9423-f41cbd0dd7fd.png)

**Comment by orlin** [comment]
Gulp also doesn't look good with light themes.  I keep my terminal dark all the time but I like to use a light Atom theme during the day which makes this half-useless, a shame because I really like the plugin.  It's the white that really needs to be replaced - perhaps text substitution just for that would be enough?

**Comment by hawkins** [comment]
A similar issue occurs on dark mode, but the issue is of course with the dark text print statements rather than the light.

**Comment by kovtunos** [comment]
As a temporary solution you can hack the atom stylesheet code: 

```css
.theme-one-light-ui {
  .gulp-control {
    .output {
      background-color: #505050;
      color: white;
      pre {
        background-color: #505050;
        color: #FFA8A8 !important;
        font-weight: bold;
        span {
          color: #ECECEC !important;
        }
      }
    }
  }
}
```
Or something like this.
